### ISSUE TITLE
Archiver crashes out with a 503 error when attempting to access reshare.r/accords/ .

### ISSUE THREAD

**Issue by boastful-inaba** [vs49688/accords-mirrorrer#1]
Log segment:
`time=2024-10-30T06:07:08.765+11:00 level=ERROR msg="error scraping" url=https://resha.re/accords/ error="HTTP 503 Service Unavailable"
time=2024-10-30T06:07:08.766+11:00 level=ERROR msg="error scraping urls" error="HTTP 503 Service Unavailable"
HTTP 503 Service Unavailable`

This is just after the long series of "fetching video channel" messages finish.

I think this is your Step 2 "Scrapes the directory listing of the assets server in case anything was missed."

Note that the server itself seems to be working OK when accessed in a web browser.

Either a fix or an option to just skip the double scan part 2 and use what was gathered in part 1 would be useful.

**Comment by vs49688** [comment]
That error should be transient, you can run it again. All the data from part 1 should still be saved.
If you want to skip it and just download, add `--dont-refresh`, does that help?

**Comment by vs49688** [comment]
![image](https://github.com/user-attachments/assets/4d15616b-22bb-4143-92e3-5369010b4e59)
They've added protection, that's why

EDIT: I've add my `state.json` to the releases page, which has the index fully populated. Use that with `--dont-refresh`

**Comment by boastful-inaba** [comment]
Alright, using your state.json with `--dont-refresh` worked.  Thanks for that, and thanks for your help in preservation efforts overall.
